### ISSUE TITLE
`OTLP_EXPORTER_OTLP_HEADERS` fail to parse with `key=value` format

### ISSUE THREAD

**Issue by parsonsmatt** [Pondidum/Trace#1]
Relevant code: https://github.com/Pondidum/Trace/blob/81804b6269802539fed209a7eb9f97bcca9ccfba/tracing/otlp_exporter.go#L44-L56

The [OTLP Exporter Configuration Reference](https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_headers) shows that these headers should be in `key=value` format.

**Comment by Pondidum** [comment]
Fixed in 71a83b8872f8016fced693e648993bd51e19cb87!  Thank you for the report and docs links!
