### ISSUE TITLE
`OTEL_RESOURCE_ATTRIBUTES` not supported

### ISSUE THREAD

**Issue by parsonsmatt** [Pondidum/Trace#3]
Docs: https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/

**Comment by Pondidum** [comment]
Hi,

While the `trace` tool doesn't explicitly read the `OTEL_RESOURCE_ATTRIBUTES` environment variable, the `resource.NewWithAttributes(...)` call does internally.

I have added a test in 722967187b2b90c909ba96f1573aafd1b5825821 to make sure of this so it doesn't get missed if something changes in the future.

**Comment by parsonsmatt** [comment]
Indeed! It's getting picked up. I've identified the real cause of my confusion. Thanks!
